const base="https://genikid-ai.github.io/imagecard/images/game-folder-gwr6v0/";
const BACKEND_URL="https://script.google.com/macros/s/AKfycbzZE3y4LMS4mxyzdlS86stqiGNyDT56krpICOsfqpeo6yzMB1aEOXd9204XIbXrNpYKHg/exec";
const GAME_CODE="LANGUAGE_CHALLENGE_UPPER",GAME_VERSION="1.0.0";
const make=(rows,type)=>rows.map(x=>type==="sound"?{word:x[0],prompt:base+x[1],success:base+x[2],answer:base+x[3]}:{word:x[0],prompt:base+x[1],answer:base+x[2]});
const sounds=make([["趴著","image-98f5c2ae.jpg","image-05ef9d72.jpg","image-bb239c82.jpg"],["皮膚","image-27b741b6.jpg","image-243ec7ca.jpg","image-f5f124b1.jpg"],["快樂","image-37eb4851.jpg","image-cc5c1a7a.jpg","image-6de6e8f1.jpg"],["唱歌","image-d1799ce0.jpg","image-35198d0d.jpg","image-05560c85.jpg"],["一棵","image-13c8500e.jpg","image-811c9801.jpg","image-6dd8ef25.jpg"],["出來","image-21a6d892.jpg","image-4dc9d449.jpg","image-a0fc3662.jpg"],["讀書","image-eed1bd56.jpg","image-79c01a88.jpg","image-3dfdadf7.jpg"]],"sound");
const pictures=make([["爸爸","image-6137a592.jpg","image-dd633db2.jpg"],["媽媽","image-cec8c8c3.jpg","image-25144c20.jpg"],["刀子","image-7c8c222d.jpg","image-d49c2180.jpg"],["桃子","image-fda9f293.jpg","image-8b8c3937.jpg"],["小牛","image-9214ffb7.jpg","image-eaabb10e.jpg"],["喝水","image-2457b85f.jpg","image-94ed5d16.jpg"],["飛機","image-af43f10a.jpg","image-9d276159.jpg"],["油漆","image-e1d6e797.jpg","image-6c83550e.jpg"],["西瓜","image-8e829c5c.jpg","image-e250e5e3.jpg"],["小豬","image-7aa8fda3.jpg","image-41610abf.jpg"]],"picture");
const app=document.querySelector("#app");let state={screen:"home",school:"至善園",className:"",seat:null,questions:[],index:0,options:[],results:[],selected:null,review:false,records:[],loading:false,saving:false,classReady:false,academicYear:"",years:[],classOptions:[],configLoading:false};
const shuffle=a=>[...a].sort(()=>Math.random()-.5),norm=v=>{v=v.trim();return v&&!v.endsWith("班")?v+"班":v},score=()=>state.results.filter(x=>x.correct).length;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
function classRecords(){return state.records.filter(r=>r.school===state.school&&(!state.className||r.className===norm(state.className)))}
async function loadAcademicYears(){if(BACKEND_URL.startsWith('__'))return;state.configLoading=true;render();try{const p=new URLSearchParams({action:'academicYears'}),res=await fetch(BACKEND_URL+'?'+p),data=await res.json();if(!data.ok)throw new Error(data.error||'讀取失敗');state.years=data.years||[];if(!state.years.includes(state.academicYear))state.academicYear=state.years[0]||'';await loadClasses()}catch(e){console.warn('學年度暫時無法讀取',e);state.configLoading=false;render()}}
async function loadClasses(){if(!state.academicYear||BACKEND_URL.startsWith('__')){state.classOptions=[];state.className='';state.configLoading=false;render();return}state.configLoading=true;state.classReady=false;state.seat=null;render();try{const p=new URLSearchParams({action:'classes',academicYear:state.academicYear,school:state.school,grade:'中班'}),res=await fetch(BACKEND_URL+'?'+p),data=await res.json();if(!data.ok)throw new Error(data.error||'讀取失敗');state.classOptions=data.classes||[];state.className=''}catch(e){console.warn('班級暫時無法讀取',e);state.classOptions=[];state.className=''}finally{state.configLoading=false;render()}}
async function syncClass(){if(!state.className.trim()||BACKEND_URL.startsWith("__"))return;state.classReady=false;state.loading=true;render();try{const p=new URLSearchParams({action:"classResults",academicYear:state.academicYear,school:state.school,className:norm(state.className)}),res=await fetch(`${BACKEND_URL}?${p}`),data=await res.json();if(!data.ok)throw new Error(data.error||"讀取失敗");state.records=data.rows.map(r=>({school:r.school,className:r.className,seat:+r.seat,score:r.score/20,results:r.questions.map(q=>({word:q.word,correct:q.result==="○"})),completedAt:r.completedAt}));state.classReady=true}catch(e){state.classReady=false;console.warn("雲端成果暫時無法讀取",e)}finally{state.loading=false;render()}}
async function saveCompleted(){const payload={action:"submit",gameCode:GAME_CODE,version:GAME_VERSION,academicYear:state.academicYear,school:state.school,className:norm(state.className),seat:String(state.seat),sessionId:crypto.randomUUID?crypto.randomUUID():String(Date.now()),questions:state.results.map(x=>({word:x.word,result:x.correct?"○":"X"}))};if(BACKEND_URL.startsWith("__"))throw new Error("後台尚未部署");const res=await fetch(BACKEND_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload)}),data=await res.json();if(!data.ok)throw new Error(data.error||"儲存失敗");return data}
function optionsFor(card,i){const pool=i<2?sounds:pictures;return shuffle([card,...shuffle(pool.filter(x=>x.word!==card.word)).slice(0,5)])}
function render(){app.innerHTML=state.screen==="home"?home():state.screen==="game"?game():state.screen==="finish"?finish():report();bind()}
function home(){const locked=new Set(classRecords().map(r=>r.seat));const schools=["至善園","至美園","至真園","復國園","文化園","富農園","而勇園"];return `<section class="panel"><header class="brand"><span class="eyebrow">語文闖關 中上</span><h1>語詞配對</h1></header><div class="identity"><label>學年度<select id="academicYear" ${state.configLoading?"disabled":""}><option value="">請選擇學年度</option>${state.years.map(x=>`<option value="${x}" ${state.academicYear===x?"selected":""}>${x}</option>`).join("")}</select></label><label>園所<select id="school">${schools.map(x=>`<option ${state.school===x?"selected":""}>${x}</option>`).join("")}</select></label><label>班級<select id="className" ${state.configLoading||!state.academicYear?"disabled":""}><option value="">${state.configLoading?"讀取中…":"請選擇班級"}</option>${state.classOptions.map(x=>`<option value="${x}" ${state.className===x?"selected":""}>${x}</option>`).join("")}</select></label></div>${state.className?(state.classReady?`<div class="seat-area"><h2>請選擇座號</h2><div class="seat-grid">${Array.from({length:30},(_,i)=>i+1).map(n=>`<button class="seat ${state.seat===n?"active":""}" data-seat="${n}" ${state.loading||!state.classReady||locked.has(n)?"disabled":""}>${n}</button>`).join("")}</div></div>`:`<div class="seat-loading">正在讀取該班座號…</div>`):""}<div class="actions"><button class="secondary" id="report" ${state.loading||!state.classReady?"disabled":""}>查看全班成果</button><button class="primary" id="start" ${state.loading||!state.classReady||state.seat===null?"disabled":""}>開始闖關</button></div><p class="note">完成後才會新增紀錄；中途返回不留下資料。</p></section>`}
function game(){const q=state.questions[state.index],showSuccess=q.success&&(state.review||state.selected===q.word),correctNow=state.selected===q.word;return `<section class="panel game-panel">${correctNow?'<div class="success-pop" role="status"><strong>答對</strong><span aria-label="讚">👍</span></div>':""}<header class="game-top"><button class="back" id="back">← 返回重選</button><div class="seat-badge">${esc(norm(state.className))}・${state.seat} 號</div><div class="round">第 ${state.index+1} 題</div></header><div class="progress">${Array.from({length:5},(_,i)=>{const r=state.results[i],c=r?(r.correct?"lit":"dim"):i===state.index?"current":"";return `<span class="star ${c}">★</span>`}).join("")}</div><div class="instruction"><span>${state.index<2?"語詞找注音":"圖片找語詞"}</span><h2>${state.review?"看看正確答案，再前往下一題":state.index<2?"找找看，哪一張是正確的注音？":"找找看，哪一張是正確的語詞？"}</h2></div><div class="play-area"><article class="prompt"><img src="${showSuccess?q.success:q.prompt}" alt="${q.word}題目圖卡"></article><div class="choices">${state.options.map(c=>{const right=c.word===q.word,wrong=state.review&&!right;return `<button class="choice ${state.review&&right?"correct":""} ${wrong?"wrong":""}" data-word="${c.word}" ${state.selected?"disabled":""}><img src="${c.answer}" alt="${c.word}選項">${wrong?'<span class="wrong-mark">×</span>':""}</button>`}).join("")}</div></div>${state.review?`<div class="review"><span>正確答案是「${q.word}」</span><button class="primary" id="next">下一題</button></div>`:""}</section>`}
function finish(){const s=score(),parts=s===5?["恭喜過關！","表現超讚！❤️"]:s>=3?["闖關完成！","回家記得多複習喔！🌟"]:["繼續加油！","多練習會越來越棒！💪"];return `<section class="panel finish"><div class="finish-message"><h1>${parts[0]}</h1><p>${parts[1]}</p></div><div class="actions"><button class="secondary" id="report">查看全班成果</button><button class="primary" id="home">回到首頁</button></div></section>`}
function report(){const rows=classRecords(),avg=rows.length?Math.round(rows.reduce((a,r)=>a+r.score*20,0)/rows.length):"—",words=[...sounds,...pictures];const accuracy=words.map(w=>{const tries=rows.flatMap(r=>r.results).filter(x=>x.word===w.word),right=tries.filter(x=>x.correct).length;return {word:w.word,tries:tries.length,rate:tries.length?Math.round(right/tries.length*100):null}});return `<section class="panel"><header class="report-head"><div><span class="eyebrow">成果預覽</span><h1>${esc(state.academicYear)}・${esc(norm(state.className)||"尚未選擇班級")}・全班成果</h1></div><button class="back" id="home">← 返回首頁</button></header><div class="summary"><div><strong>${rows.length}</strong><span>完成人數</span></div><div><strong>${avg}${avg!=="—"?" 分":""}</strong><span>平均成績</span></div><div><strong>${rows.filter(r=>r.score===5).length}</strong><span>滿分人數</span></div></div><div class="table-wrap"><table><thead><tr><th>座號</th>${[1,2,3,4,5].map(n=>`<th>第${n}題</th>`).join("")}<th>成績</th><th>其他成績</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td>${r.seat} 號</td>${r.results.map(x=>`<td>${x.word}<b class="${x.correct?"ok":"miss"}">${x.correct?"○":"X"}</b></td>`).join("")}<td><strong>${r.score*20} 分</strong></td><td class="hint">可擴充</td></tr>`).join(""):`<tr><td colspan="8" class="empty">目前還沒有完成紀錄</td></tr>`}</tbody></table></div><section class="accuracy"><h2>各語詞正確率</h2><div class="accuracy-grid">${accuracy.map(x=>`<div><span>${x.word}</span><strong>${x.rate===null?"—":x.rate+"%"}</strong><small>${x.tries?`作答 ${x.tries} 次`:"尚未出題"}</small></div>`).join("")}</div></section></section>`}
function bind(){const $=s=>document.querySelector(s);if(state.screen==="home"){$("#academicYear").onchange=e=>{state.academicYear=e.target.value;loadClasses()};$("#school").onchange=e=>{state.school=e.target.value;loadClasses()};$("#className").onchange=e=>{state.className=e.target.value;state.seat=null;state.classReady=false;if(state.className)syncClass();else render()};document.querySelectorAll("[data-seat]").forEach(b=>b.onclick=()=>{state.seat=+b.dataset.seat;render()});$("#start").onclick=start;$("#report").onclick=()=>{state.screen="report";render()}}else if(state.screen==="game"){$("#back").onclick=reset;document.querySelectorAll("[data-word]").forEach(b=>b.onclick=()=>answer(b.dataset.word));if($("#next"))$("#next").onclick=advance}else if(state.screen==="finish"){$("#home").onclick=reset;$("#report").onclick=()=>{state.screen="report";render()}}else $("#home").onclick=()=>{state.screen="home";render()}}
function start(){state.questions=[...shuffle(sounds).slice(0,2),...shuffle(pictures).slice(0,3)];state.index=0;state.results=[];state.selected=null;state.review=false;state.options=optionsFor(state.questions[0],0);state.screen="game";render()}
function answer(word){if(state.selected)return;const q=state.questions[state.index],correct=word===q.word;state.selected=word;state.results.push({word:q.word,correct});if(correct){render();setTimeout(advance,1200)}else{state.review=true;render()}}
async function advance(){if(state.index===4){if(state.saving)return;state.saving=true;try{await saveCompleted();const record={school:state.school,className:norm(state.className),seat:state.seat,score:score(),results:state.results,completedAt:new Date().toISOString()};state.records=state.records.filter(r=>!(r.school===record.school&&r.className===record.className&&r.seat===record.seat));state.records.push(record);localStorage.setItem("language-game-upper-demo",JSON.stringify(state.records));state.screen="finish";render()}catch(e){state.saving=false;alert("成績尚未儲存，請檢查網路後再按一次下一題。\n"+e.message)}return}state.index++;state.selected=null;state.review=false;state.options=optionsFor(state.questions[state.index],state.index);render()}
function reset(){state.screen="home";state.seat=null;state.questions=[];state.index=0;state.options=[];state.results=[];state.selected=null;state.review=false;render()}
render();loadAcademicYears();
