const base="https://genikid-ai.github.io/imagecard/images/game-folder-gwr6v0/";
const BACKEND_URL="https://script.google.com/macros/s/AKfycbzZE3y4LMS4mxyzdlS86stqiGNyDT56krpICOsfqpeo6yzMB1aEOXd9204XIbXrNpYKHg/exec";
const GAME_CODE="LANGUAGE_CHALLENGE_UPPER",GAME_VERSION="1.0.0";
const make=(rows,type)=>rows.map(x=>type==="sound"?{word:x[0],prompt:base+x[1],success:base+x[2],answer:base+x[3]}:{word:x[0],prompt:base+x[1],answer:base+x[2]});
const sounds=make([["趴著","image-98f5c2ae.jpg","image-05ef9d72.jpg","image-bb239c82.jpg"],["皮膚","image-27b741b6.jpg","image-243ec7ca.jpg","image-f5f124b1.jpg"],["快樂","image-37eb4851.jpg","image-cc5c1a7a.jpg","image-6de6e8f1.jpg"],["唱歌","image-d1799ce0.jpg","image-35198d0d.jpg","image-05560c85.jpg"],["一棵","image-13c8500e.jpg","image-811c9801.jpg","image-6dd8ef25.jpg"],["出來","image-21a6d892.jpg","image-4dc9d449.jpg","image-a0fc3662.jpg"],["讀書","image-eed1bd56.jpg","image-79c01a88.jpg","image-3dfdadf7.jpg"]],"sound");
const pictures=make([["爸爸","image-6137a592.jpg","image-dd633db2.jpg"],["媽媽","image-cec8c8c3.jpg","image-25144c20.jpg"],["刀子","image-7c8c222d.jpg","image-d49c2180.jpg"],["桃子","image-fda9f293.jpg","image-8b8c3937.jpg"],["小牛","image-9214ffb7.jpg","image-eaabb10e.jpg"],["喝水","image-2457b85f.jpg","image-94ed5d16.jpg"],["飛機","image-af43f10a.jpg","image-9d276159.jpg"],["油漆","image-e1d6e797.jpg","image-6c83550e.jpg"],["西瓜","image-8e829c5c.jpg","image-e250e5e3.jpg"],["小豬","image-7aa8fda3.jpg","image-41610abf.jpg"]],"picture");
const app=document.querySelector("#app");let state={screen:"home",school:"",className:"",seat:null,questions:[],index:0,options:[],results:[],selected:null,review:false,records:[],loading:false,saving:false,saveError:"",sessionId:"",autoAdvanceTimer:null,classReady:false,academicYear:"",years:[],schools:[],classOptions:[],configLoading:false};
const shuffle=a=>[...a].sort(()=>Math.random()-.5),norm=v=>{v=v.trim();return v&&!v.endsWith("班")?v+"班":v},score=()=>state.results.filter(x=>x.correct).length;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
function classRecords(){return state.records.filter(r=>r.school===state.school&&(!state.className||r.className===norm(state.className)))}
function balancedPick(pool,count){const totals=Object.fromEntries(pool.map(card=>[card.word,0]));classRecords().forEach(record=>record.results.forEach(result=>{if(Object.prototype.hasOwnProperty.call(totals,result.word))totals[result.word]++}));return shuffle(pool).sort((a,b)=>totals[a.word]-totals[b.word]).slice(0,count)}
function classAccuracy(){const rows=classRecords(),words=[...sounds,...pictures];return words.map(w=>{const tries=rows.flatMap(r=>r.results).filter(x=>x.word===w.word),right=tries.filter(x=>x.correct).length;return {word:w.word,tries:tries.length,right,rate:tries.length?Math.round(right/tries.length*100):null}})}
function suggestedWords(){return classAccuracy().filter(x=>x.tries>=3&&x.rate<60).sort((a,b)=>a.rate-b.rate||a.word.localeCompare(b.word,"zh-Hant"))}
function safeFilePart(value){return String(value||"").replace(/[\\/:*?"<>|]/g,"-").trim()}
function roundedRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function downloadReportJpg(){const review=suggestedWords(),canvas=document.createElement("canvas"),ctx=canvas.getContext("2d"),font='"Noto Sans TC","Microsoft JhengHei",sans-serif';canvas.width=1200;canvas.height=1600;ctx.fillStyle="#fffaf0";ctx.fillRect(0,0,1200,1600);ctx.strokeStyle="#6f927e";ctx.lineWidth=12;roundedRect(ctx,38,38,1124,1524,34);ctx.stroke();ctx.textAlign="center";ctx.fillStyle="#34463f";ctx.font=`700 64px ${font}`;ctx.fillText("班級複習參考",600,170);ctx.fillStyle="#4d735f";ctx.font=`700 48px ${font}`;ctx.fillText(state.academicYear,600,270);ctx.font=`700 44px ${font}`;ctx.fillText(`${state.school}・${norm(state.className)}`,600,350);ctx.strokeStyle="#dce7de";ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(110,410);ctx.lineTo(1090,410);ctx.stroke();ctx.fillStyle="#34463f";ctx.font=`700 48px ${font}`;ctx.fillText("建議複習語詞",600,500);if(review.length){review.forEach((item,index)=>{const col=index%3,row=Math.floor(index/3),x=80+col*360,y=560+row*140;ctx.fillStyle="#eaf1e9";roundedRect(ctx,x,y,320,104,24);ctx.fill();ctx.fillStyle="#34463f";ctx.font=`700 38px ${font}`;ctx.fillText(item.word,x+160,y+66)})}else{ctx.fillStyle="#718079";ctx.font=`500 38px ${font}`;ctx.fillText("目前沒有建議複習的語詞",600,650)}canvas.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`${safeFilePart(state.academicYear)}_${safeFilePart(state.school)}_${safeFilePart(norm(state.className))}_闖關成果.jpg`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)},"image/jpeg",.94)}
async function loadAcademicYears(){if(BACKEND_URL.startsWith('__'))return;state.configLoading=true;render();try{const p=new URLSearchParams({action:'academicYears'}),res=await fetch(BACKEND_URL+'?'+p),data=await res.json();if(!data.ok)throw new Error(data.error||'讀取失敗');state.years=data.years||[];if(!state.years.includes(state.academicYear))state.academicYear=state.years[0]||'';await loadSchools()}catch(e){console.warn('學年度暫時無法讀取',e);state.configLoading=false;render()}}
async function loadSchools(){if(!state.academicYear||BACKEND_URL.startsWith('__')){state.schools=[];state.school='';state.classOptions=[];state.className='';state.configLoading=false;render();return}state.configLoading=true;state.classReady=false;state.seat=null;render();try{const p=new URLSearchParams({action:'schools',academicYear:state.academicYear,grade:'中班'}),res=await fetch(BACKEND_URL+'?'+p),data=await res.json();if(!data.ok)throw new Error(data.error||'讀取失敗');state.schools=data.schools||[];if(!state.schools.includes(state.school))state.school=state.schools[0]||'';await loadClasses()}catch(e){console.warn('園所暫時無法讀取',e);state.schools=[];state.school='';state.classOptions=[];state.className='';state.configLoading=false;render()}}
async function loadClasses(){if(!state.academicYear||!state.school||BACKEND_URL.startsWith('__')){state.classOptions=[];state.className='';state.configLoading=false;render();return}state.configLoading=true;state.classReady=false;state.seat=null;render();try{const p=new URLSearchParams({action:'classes',academicYear:state.academicYear,school:state.school,grade:'中班'}),res=await fetch(BACKEND_URL+'?'+p),data=await res.json();if(!data.ok)throw new Error(data.error||'讀取失敗');state.classOptions=data.classes||[];state.className=''}catch(e){console.warn('班級暫時無法讀取',e);state.classOptions=[];state.className=''}finally{state.configLoading=false;render()}}
async function syncClass(){if(!state.className.trim()||BACKEND_URL.startsWith("__"))return;state.classReady=false;state.loading=true;render();try{const p=new URLSearchParams({action:"classResults",academicYear:state.academicYear,school:state.school,className:norm(state.className)}),res=await fetch(`${BACKEND_URL}?${p}`),data=await res.json();if(!data.ok)throw new Error(data.error||"讀取失敗");state.records=data.rows.map(r=>({school:r.school,className:r.className,seat:+r.seat,score:r.score/20,results:r.questions.map(q=>({word:q.word,correct:q.result==="○"})),completedAt:r.completedAt}));state.classReady=true}catch(e){state.classReady=false;console.warn("雲端成果暫時無法讀取",e)}finally{state.loading=false;render()}}
async function fetchJsonWithTimeout(url,options={},timeout=15000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const res=await fetch(url,{...options,signal:controller.signal});return await res.json()}catch(e){if(e.name==="AbortError")throw new Error("後台回應逾時");throw e}finally{clearTimeout(timer)}}
async function verifyCompleted(){try{const p=new URLSearchParams({action:"classResults",academicYear:state.academicYear,school:state.school,className:norm(state.className)}),data=await fetchJsonWithTimeout(`${BACKEND_URL}?${p}`,{},8000);return Boolean(data.ok&&(data.rows||[]).some(r=>+r.seat===state.seat))}catch{return false}}
async function saveCompleted(){const payload={action:"submit",gameCode:GAME_CODE,version:GAME_VERSION,academicYear:state.academicYear,school:state.school,className:norm(state.className),seat:String(state.seat),sessionId:state.sessionId,questions:state.results.map(x=>({word:x.word,result:x.correct?"○":"X"}))};if(BACKEND_URL.startsWith("__"))throw new Error("後台尚未部署");try{const data=await fetchJsonWithTimeout(BACKEND_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload)});if(!data.ok)throw new Error(data.error||"儲存失敗");return data}catch(e){if(await verifyCompleted())return {ok:true,verified:true};throw e}}
function optionsFor(card,i){const pool=i<2?sounds:pictures;return shuffle([card,...shuffle(pool.filter(x=>x.word!==card.word)).slice(0,5)])}
function render(){app.innerHTML=state.screen==="home"?home():state.screen==="game"?game():state.screen==="finish"?finish():report();bind()}
function home(){const locked=new Set(classRecords().map(r=>r.seat));return `<section class="panel"><header class="brand"><span class="eyebrow">語文闖關 中上</span><h1>語詞配對</h1></header><div class="identity"><label>學年度<select id="academicYear" ${state.configLoading?"disabled":""}><option value="">請選擇學年度</option>${state.years.map(x=>`<option value="${x}" ${state.academicYear===x?"selected":""}>${x}</option>`).join("")}</select></label><label>園所<select id="school" ${state.configLoading||!state.academicYear?"disabled":""}><option value="">${state.configLoading?"讀取中…":"請選擇園所"}</option>${state.schools.map(x=>`<option value="${x}" ${state.school===x?"selected":""}>${x}</option>`).join("")}</select></label><label>班級<select id="className" ${state.configLoading||!state.academicYear||!state.school?"disabled":""}><option value="">${state.configLoading?"讀取中…":"請選擇班級"}</option>${state.classOptions.map(x=>`<option value="${x}" ${state.className===x?"selected":""}>${x}</option>`).join("")}</select></label></div>${state.className?(state.classReady?`<div class="seat-area"><h2>請選擇座號</h2><div class="seat-grid">${Array.from({length:30},(_,i)=>i+1).map(n=>`<button class="seat ${state.seat===n?"active":""}" data-seat="${n}" ${state.loading||!state.classReady||locked.has(n)?"disabled":""}>${n}</button>`).join("")}</div></div>`:`<div class="seat-loading">正在讀取該班座號…</div>`):""}<div class="actions"><button class="secondary" id="report" ${state.loading||!state.classReady?"disabled":""}>查看全班成果</button><button class="primary" id="start" ${state.loading||!state.classReady||state.seat===null?"disabled":""}>開始闖關</button></div><p class="note">完成後才會新增紀錄；中途返回不留下資料。</p></section>`}
function game(){const q=state.questions[state.index],showSuccess=q.success&&(state.review||state.selected===q.word),correctNow=state.selected===q.word;return `<section class="panel game-panel">${correctNow&&!state.saving?'<div class="success-pop" role="status"><strong>答對</strong><span aria-label="讚">👍</span></div>':""}${state.saving?'<div class="save-status" role="status"><div class="save-spinner"></div><strong>成績儲存中…</strong><span>請稍候，不要關閉畫面</span></div>':state.saveError?`<div class="save-status save-failed" role="alert"><strong>成績尚未儲存</strong><span>${esc(state.saveError)}</span><button class="primary" id="retrySave">重新儲存</button></div>`:""}<header class="game-top"><button class="back" id="back" ${state.saving?"disabled":""}>← 返回重選</button><div class="seat-badge">${esc(norm(state.className))}・${state.seat} 號</div><div class="round">第 ${state.index+1} 題</div></header><div class="progress">${Array.from({length:5},(_,i)=>{const r=state.results[i],c=r?(r.correct?"lit":"dim"):i===state.index?"current":"";return `<span class="star ${c}">★</span>`}).join("")}</div><div class="instruction"><span>${state.index<2?"語詞找注音":"圖片找語詞"}</span><h2>${state.review?"看看正確答案，再前往下一題":state.index<2?"找找看，哪一張是正確的注音？":"找找看，哪一張是正確的語詞？"}</h2></div><div class="play-area"><article class="prompt"><img src="${showSuccess?q.success:q.prompt}" alt="${q.word}題目圖卡"></article><div class="choices">${state.options.map(c=>{const right=c.word===q.word,wrong=state.review&&!right;return `<button class="choice ${state.review&&right?"correct":""} ${wrong?"wrong":""}" data-word="${c.word}" ${state.selected?"disabled":""}><img src="${c.answer}" alt="${c.word}選項">${wrong?'<span class="wrong-mark">×</span>':""}</button>`}).join("")}</div></div>${state.review?`<div class="review"><span>正確答案是「${q.word}」</span><button class="primary" id="next" ${state.saving||state.saveError?"disabled":""}>下一題</button></div>`:""}</section>`}
function finish(){const s=score(),parts=s===5?["恭喜過關！","表現超讚！❤️"]:s>=3?["闖關完成！","回家記得多複習喔！🌟"]:["繼續加油！","多練習會越來越棒！💪"];return `<section class="panel finish"><div class="finish-message"><h1>${parts[0]}</h1><p>${parts[1]}</p></div><div class="actions"><button class="secondary" id="report">查看全班成果</button><button class="primary" id="home">回到首頁</button></div></section>`}
function report(){const rows=classRecords(),avg=rows.length?Math.round(rows.reduce((a,r)=>a+r.score*20,0)/rows.length):"—",accuracy=classAccuracy(),review=suggestedWords();return `<section class="panel"><header class="report-head"><div><span class="eyebrow">成果預覽</span><h1>${esc(state.academicYear)}・${esc(norm(state.className)||"尚未選擇班級")}・全班成果</h1></div><div class="report-actions"><button class="secondary" id="downloadJpg">下載闖關成果 JPG</button><button class="back" id="home">← 返回首頁</button></div></header><div class="summary"><div><strong>${rows.length}</strong><span>完成人數</span></div><div><strong>${avg}${avg!=="—"?" 分":""}</strong><span>平均成績</span></div><div><strong>${rows.filter(r=>r.score===5).length}</strong><span>滿分人數</span></div></div><div class="table-wrap"><table><thead><tr><th>座號</th>${[1,2,3,4,5].map(n=>`<th>第${n}題</th>`).join("")}<th>成績</th><th>其他成績</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td>${r.seat} 號</td>${r.results.map(x=>`<td>${x.word}<b class="${x.correct?"ok":"miss"}">${x.correct?"○":"X"}</b></td>`).join("")}<td><strong>${r.score*20} 分</strong></td><td class="hint">可擴充</td></tr>`).join(""):`<tr><td colspan="8" class="empty">目前還沒有完成紀錄</td></tr>`}</tbody></table></div><section class="accuracy"><h2>各語詞正確率</h2><p class="section-note">出題次數會在同一班級中自動平均；未滿 3 次的語詞暫不列入複習建議。</p><div class="accuracy-grid">${accuracy.map(x=>`<div><span>${x.word}</span><strong>${x.rate===null?"—":x.rate+"%"}</strong><small>${x.tries?`答對 ${x.right}／出題 ${x.tries} 次`:"尚未出題"}</small></div>`).join("")}</div></section><section class="review-words"><h2>建議複習語詞</h2><p class="section-note">出題至少 3 次且正確率低於 60% 才會列入。可依班級學習情況，彈性安排複習。</p>${review.length?`<div class="review-grid">${review.map(x=>`<div><strong>${x.word}</strong><span>${x.rate}%</span><small>答對 ${x.right}／出題 ${x.tries} 次</small></div>`).join("")}</div>`:`<div class="review-empty">${rows.length?"目前沒有符合複習建議條件的語詞。":"完成闖關後，這裡會整理建議複習的語詞。"}</div>`}</section></section>`}
function bind(){const $=s=>document.querySelector(s);if(state.screen==="home"){$("#academicYear").onchange=e=>{state.academicYear=e.target.value;loadSchools()};$("#school").onchange=e=>{state.school=e.target.value;loadClasses()};$("#className").onchange=e=>{state.className=e.target.value;state.seat=null;state.classReady=false;if(state.className)syncClass();else render()};document.querySelectorAll("[data-seat]").forEach(b=>b.onclick=()=>{state.seat=+b.dataset.seat;render()});$("#start").onclick=start;$("#report").onclick=()=>{state.screen="report";render()}}else if(state.screen==="game"){$("#back").onclick=reset;document.querySelectorAll("[data-word]").forEach(b=>b.onclick=()=>answer(b.dataset.word));if($("#next"))$("#next").onclick=advance;if($("#retrySave"))$("#retrySave").onclick=advance}else if(state.screen==="finish"){$("#home").onclick=reset;$("#report").onclick=()=>{state.screen="report";render()}}else{$("#home").onclick=()=>{state.screen="home";render()};$("#downloadJpg").onclick=downloadReportJpg}}
function start(){state.questions=[...balancedPick(sounds,2),...balancedPick(pictures,3)];state.index=0;state.results=[];state.selected=null;state.review=false;state.saving=false;state.saveError="";state.sessionId=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`;state.options=optionsFor(state.questions[0],0);state.screen="game";render()}
function answer(word){if(state.selected)return;const q=state.questions[state.index],correct=word===q.word;state.selected=word;state.results.push({word:q.word,correct});if(correct){render();state.autoAdvanceTimer=setTimeout(()=>{state.autoAdvanceTimer=null;if(state.screen==="game")advance()},1200)}else{state.review=true;render()}}
async function advance(){if(state.screen!=="game")return;if(state.index===4){if(state.saving)return;state.saving=true;state.saveError="";render();try{await saveCompleted();const record={school:state.school,className:norm(state.className),seat:state.seat,score:score(),results:state.results,completedAt:new Date().toISOString()};state.records=state.records.filter(r=>!(r.school===record.school&&r.className===record.className&&r.seat===record.seat));state.records.push(record);localStorage.setItem("language-game-upper-demo",JSON.stringify(state.records));state.saving=false;state.screen="finish";render()}catch(e){state.saving=false;state.saveError=e.message||"請檢查網路後重新儲存。";render()}return}state.index++;state.selected=null;state.review=false;state.options=optionsFor(state.questions[state.index],state.index);render()}
function reset(){if(state.autoAdvanceTimer)clearTimeout(state.autoAdvanceTimer);state.autoAdvanceTimer=null;state.screen="home";state.seat=null;state.questions=[];state.index=0;state.options=[];state.results=[];state.selected=null;state.review=false;state.saving=false;state.saveError="";state.sessionId="";render()}
render();loadAcademicYears();
